/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DiffVisualisation.java
 *
 * Created on Jul 19, 2011, 8:16:20 PM
 */
package xmlcompare;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JSplitPane;
import javax.xml.stream.XMLStreamException;
import xmlcompare.impl.gui.ViewWithControls;
import xmlcompare.impl.gui.XmlViewerComponent;

/**
 *
 * @author jvanek
 */
public class DiffVisualisation extends javax.swing.JFrame {

    /*
     * Creates new form DiffVisualisation
     */
    public DiffVisualisation() throws FileNotFoundException, XMLStreamException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(400);

        jPanel2.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(jPanel2);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    DiffVisualisation df = new DiffVisualisation();
                    df.mobilize();
                    df.setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(DiffVisualisation.class.getName()).log(Level.SEVERE, null, ex);
                } catch (XMLStreamException ex) {
                    Logger.getLogger(DiffVisualisation.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    private void mobilize() throws FileNotFoundException, XMLStreamException {
        XmlViewerComponent xvv;
        //xvv=new XmlViewerComponent(new File("tests/longer.xml"));
        xvv = new XmlViewerComponent(new File("tests/working/pokusny2_part_00007.xml"));
        //xvv=new XmlViewerComponent(new File("tests/abcd1.xml"))

        ViewWithControls vwc1 = new ViewWithControls(0);

        vwc1.setXmlViewerComponent(xvv);
        jPanel1.add(vwc1);
        jPanel1.validate();

        ViewWithControls vwc = new ViewWithControls(1);
        XmlViewerComponent xvv2;
        xvv2 = new XmlViewerComponent(new File("tests/longer.xml"));
        vwc.setXmlViewerComponent(xvv2);
        jPanel2.add(vwc);
        jPanel2.validate();

        jSplitPane1.validate();
    }

    public void setLeftComponent(JComponent j) {
        jPanel1.removeAll();
        jPanel1.add(j);
        jPanel1.validate();

    }

    public void setRightComponent(JComponent j) {
        jPanel2.removeAll();
        jPanel2.add(j);
        jPanel2.validate();

    }

    public JSplitPane getjSplitPane1() {
        return jSplitPane1;
    }

}
